"""added table categories and added fk to tasks

Revision ID: 390e0e4c6875
Revises: 87699fd8c967
Create Date: 2026-05-14 16:59:08.223646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390e0e4c6875'
down_revision: Union[str, Sequence[str], None] = '87699fd8c967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_category_id_categories'), 'tasks', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_category_id_categories'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
