"""added column priority to tasks table

Revision ID: 87699fd8c967
Revises: 4cfd4f5ffd49
Create Date: 2026-05-14 16:44:36.746475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "87699fd8c967"
down_revision: Union[str, Sequence[str], None] = "4cfd4f5ffd49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("priority", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "priority")
    # ### end Alembic commands ###
